### ISSUE TITLE
client9/mispell is unmaintained

### ISSUE THREAD

**Issue by ccoVeille** [goyek/template#78]
https://github.com/client9/misspell last commit is from 2018

golangci-lint forked it and maintain it

You can see it here
 https://github.com/client9/misspell/issues/197#issuecomment-1596318684

So maybe you could switch to https://github.com/golangci/misspell

**Comment by pellared** [comment]
First of all, thanks for the issue.

Is there any functional reason why we would like to switch the fork?

I do not see any outstanding features/bugfixes: https://github.com/golangci/misspell/compare/v0.3.5...master

**Comment by ccoVeille** [comment]
Right now, no.

So maybe you could simply keep using client9 one, but I wanted to inform you the lib was maintained by golangci team

https://github.com/golangci/misspell/issues/4#issue-1860198265

**Comment by pellared** [comment]
Thanks. My understanding is that they mainly maintain it so that they can use it here: https://github.com/golangci/golangci-lint/blob/95fc378f0ea5073c93ac490c751079ecaf3bbb56/pkg/golinters/misspell/misspell.go

Closing for now.
